### ISSUE TITLE
Start of Transfer Detection is incorrect.

### ISSUE THREAD

**Issue by emrainey** [OpenCyphal-Garage/libudpard#19]
start of transfer is indicated by a zero, not a 1.

`out->start_of_transfer   = (((frame->udp_cyphal_header.frame_index_eot) & (UDPARD_MAX_FRAME_INDEX)) == 1);`

Should be 

`out->start_of_transfer   = (((frame->udp_cyphal_header.frame_index_eot) & (UDPARD_MAX_FRAME_INDEX)) == 0);`

**Comment by emrainey** [comment]
This was found during Service transfers but I would imagine it's happening all the time?

**Comment by lydia-at-amazon** [comment]
Hey Erik, thanks for pointing this out. 

Looks like there a couple of things we need to change. 

We are incorrectly setting the frame index to 1 instead of 0 when we call `txMakeFrameHeader` for both single frame transfers and multiframe transfers:

1. Single frame transfers: https://github.com/OpenCyphal-Garage/libudpard/blob/main/libudpard/udpard.c#L445
2. For multiframe transfers, we need to:
- Increment the frame index **after** we call `txMakeFrameHeader`: https://github.com/OpenCyphal-Garage/libudpard/blob/main/libudpard/udpard.c#L560
- Change this check from `(frame->start_of_transfer && frame->frame_index != 1U)` to `(frame->start_of_transfer && frame->frame_index != 0U)`: https://github.com/OpenCyphal-Garage/libudpard/blob/main/libudpard/udpard.c#L994

I think there might be a few other places we need to update the logic as well.

**Comment by lydia-at-amazon** [comment]
Fixed by https://github.com/OpenCyphal-Garage/libudpard/pull/27
